# File operations exclusions ? comma-separated list
# Used only for initialization when creating a new project.
# After that, user's changes in DB take effect.
fileops.exclusions=.git,.idea,.gradle,.vscode,.veai,node_modules,build,target,dist,out,.env,*.key,*.pem,*.p12,*.jks,*.keystore
